const books = [
  {
    slug: "woqoot-al-salah",
    name: "كِتَاب وَقُوتِ الصَّلاَة",
    order: 1,
    page: 33,
  },
  { slug: "al-tahara", name: "كتاب الطهارة", order: 2, page: 43 },
  { slug: "al-salah", name: "كتاب الصلاة", order: 3, page: 79 },
  { slug: "al-sahw", name: "كتاب السهو", order: 4, page: 103 },
  { slug: "al-jumua", name: "كتاب الجمعة", order: 5, page: 105 },
  {
    slug: "al-salah-fi-ramadan",
    name: "كتاب الصلاة في رمضان",
    order: 6,
    page: 115,
  },
  { slug: "salat-al-layl", name: "كتاب صلاة الليل", order: 7, page: 119 },
  { slug: "salat-al-jamaa", name: "كتاب صلاة الجماعة", order: 8, page: 129 },
  {
    slug: "qasr-al-salah-fi-al-safar",
    name: "كتاب قصر الصلاة في السفر",
    order: 9,
    page: 139,
  },
  { slug: "al-eidayn", name: "كتاب العيدين", order: 10, page: 163 },
  { slug: "salat-al-khawf", name: "كتاب صلاة الخوف", order: 11, page: 167 },
  { slug: "salat-al-kusoof", name: "كتاب صلاة الكسوف", order: 12, page: 169 },
  { slug: "al-istisqaa", name: "كتاب الاستسقاء", order: 13, page: 173 },
  { slug: "al-qibla", name: "كتاب القبلة", order: 14, page: 177 },
  { slug: "al-quran", name: "كتاب القرآن", order: 15, page: 181 },
  { slug: "al-janaaiz", name: "كتاب الجنائز", order: 16, page: 195 },
  { slug: "al-zakat", name: "كتاب الزكاة", order: 17, page: 211 },
  { slug: "al-siyam", name: "كتاب الصيام", order: 18, page: 239 },
  { slug: "al-itikaf", name: "كتاب الاعتكاف", order: 19, page: 257 },
];

const chapters = [
  // كتاب وقوت الصلاة
  {
    bookSlug: "woqoot-al-salah",
    name: "بَاب وُقُوتِ الصَّلاَة",
    order: 1,
    page: 33,
  },
  {
    bookSlug: "woqoot-al-salah",
    name: "بَاب وَقْتِ الجُمُعَة",
    order: 2,
    page: 36,
  },
  {
    bookSlug: "woqoot-al-salah",
    name: "بَاب مَنْ أَدْرَكَ رَكْعَةً مِنَ الصَّلاَة",
    order: 3,
    page: 37,
  },
  {
    bookSlug: "woqoot-al-salah",
    name: "بَاب مَا جَاءَ فِي دُلُوكِ الشَّمْسِ وَغَسَقِ اللَّيْل",
    order: 4,
    page: 38,
  },
  {
    bookSlug: "woqoot-al-salah",
    name: "بَاب جَامِع الوُقُوت",
    order: 5,
    page: 39,
  },
  {
    bookSlug: "woqoot-al-salah",
    name: "بَاب النَّوْم عَنِ الصَّلاَة",
    order: 6,
    page: 40,
  },
  {
    bookSlug: "woqoot-al-salah",
    name: "بَاب النَّهْي عَنِ الصَّلاَة بِالهَاجِرَة",
    order: 7,
    page: 41,
  },
  {
    bookSlug: "woqoot-al-salah",
    name: "بَاب النَّهْي عَنْ دُخُولِ المَسْجِد بِرِيحِ الثُّوم، وَتَغطِيَة الفَم",
    order: 8,
    page: 42,
  },

  // كتاب الطهارة
  {
    bookSlug: "al-tahara",
    name: "بَاب العَمَل فِي الوُضُوء",
    order: 1,
    page: 43,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب وُضُوء النَّائِم إِذَا قَامَ إِلَى الصَّلاَة",
    order: 2,
    page: 45,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب الطُّهُور لِلْوُضُوء",
    order: 3,
    page: 45,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب مَا لاَ يَجِب مِنْهُ الوُضُوء",
    order: 4,
    page: 48,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب تَرْكِ الوُضُوء مِمَّا مَسَّتْهُ النَّار",
    order: 5,
    page: 49,
  },
  { bookSlug: "al-tahara", name: "بَاب جَامِع الوُضُوء", order: 6, page: 50 },
  {
    bookSlug: "al-tahara",
    name: "بَاب مَا جَاءَ فِي المَسْح بِالرَّأْس وَالأُذُنَيْن",
    order: 7,
    page: 54,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب مَا جَاءَ فِي المَسْح عَلَى الخُفَّيْن",
    order: 8,
    page: 55,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب العَمَل فِي المَسْح عَلَى الخُفَّيْن",
    order: 9,
    page: 57,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب مَا جَاءَ فِي الرُّعَاف",
    order: 10,
    page: 57,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب العَمَل فِي الرُّعَاف",
    order: 11,
    page: 58,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب العَمَل فِيمَن غَلَبَ عَلَيْه الدَّم مِن جُرْح أَو رُعَاف",
    order: 12,
    page: 58,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب الوُضُوء مِنَ المَذْي",
    order: 13,
    page: 59,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب الرُّخْصَة فِي تَرْكِ الوُضُوء مِنَ المَذْي",
    order: 14,
    page: 60,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب الوُضُوء مِن مَسِّ الفَرْج",
    order: 15,
    page: 60,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب الوُضُوء مِن قُبْلَة الرَّجُل امْرَأَتَه",
    order: 16,
    page: 62,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب العَمَل فِي غُسْل الجَنَابَة",
    order: 17,
    page: 63,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب وَاجِب الغُسْل إِذَا الْتَقَى الخِتَانَان",
    order: 18,
    page: 63,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب وُضُوء الجُنُب إِذَا أَرَادَ أَن يَطْعَمَ أَو يَقْبَل أَن يَغْتَسِل",
    order: 19,
    page: 65,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب إِعَادَة الجُنُب الصَّلاَة، وَغُسْلِه إِذَا صَلَّى وَلَمْ يَذْكُر، وَغُسْلِه ثَوْبَه",
    order: 20,
    page: 65,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب غُسْل المَرْأَة إِذَا رَأَت فِي المَنَام مِثْل مَا يَرَى الرَّجُل",
    order: 21,
    page: 67,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب جَامِع غُسْل الجَنَابَة",
    order: 22,
    page: 68,
  },
  {
    bookSlug: "al-tahara",
    name: "هَذَا بَابٌ فِي التَّيَمُّم",
    order: 23,
    page: 69,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب العَمَل فِي التَّيَمُّم",
    order: 24,
    page: 70,
  },
  { bookSlug: "al-tahara", name: "بَاب تَيَمُّم الجُنُب", order: 25, page: 70 },
  {
    bookSlug: "al-tahara",
    name: "بَاب مَا يَحِلُّ لِلرَّجُل مِن امْرَأَتِه وَهِيَ حَائِض",
    order: 26,
    page: 71,
  },
  { bookSlug: "al-tahara", name: "بَاب طُهْر الحَائِض", order: 27, page: 72 },
  { bookSlug: "al-tahara", name: "بَاب جَامِع الحَيْضَة", order: 28, page: 73 },
  { bookSlug: "al-tahara", name: "بَاب المُسْتَحَاضَة", order: 29, page: 74 },
  {
    bookSlug: "al-tahara",
    name: "بَاب مَا جَاءَ فِي بَوْل الصَّبِيّ",
    order: 30,
    page: 75,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب مَا جَاءَ فِي البَوْل قَائِمًا وَغَيْرِه",
    order: 31,
    page: 76,
  },
  {
    bookSlug: "al-tahara",
    name: "بَاب مَا جَاءَ فِي السِّوَاك",
    order: 32,
    page: 77,
  },

  // كتاب الصلاة
  {
    bookSlug: "al-salah",
    name: "بَاب مَا جَاءَ فِي النِّدَاء لِلصَّلاَة",
    order: 1,
    page: 79,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب النِّدَاء فِي السَّفَر وَعَلَى غَيْر وُضُوء",
    order: 2,
    page: 82,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب قَدْر السُّحُور مِنَ النِّدَاء",
    order: 3,
    page: 83,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب افْتِتَاح الصَّلاَة",
    order: 4,
    page: 84,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب القِرَاءَة فِي المَغْرِب وَالعِشَاء",
    order: 5,
    page: 86,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب العَمَل فِي القِرَاءَة",
    order: 6,
    page: 87,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب القِرَاءَة فِي الصُّبْح",
    order: 7,
    page: 89,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب مَا جَاءَ فِي أُمِّ القُرْآن",
    order: 8,
    page: 89,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب القِرَاءَة خَلْف الإِمَام فِيمَا لاَ يَجْهَر فِيه بِالقِرَاءَة",
    order: 9,
    page: 90,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب تَرْكِ القِرَاءَة خَلْف الإِمَام فِيمَا جَهَرَ فِيه",
    order: 10,
    page: 92,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب مَا جَاءَ فِي التَّأْمِين خَلْف الإِمَام",
    order: 11,
    page: 93,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب العَمَل فِي الجُلُوس فِي الصَّلاَة",
    order: 12,
    page: 94,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب التَّشَهُّد فِي الصَّلاَة",
    order: 13,
    page: 95,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب مَا يَفْعَل مَن رَفَعَ رَأْسَه قَبْلَ الإِمَام",
    order: 14,
    page: 97,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب مَا يَفْعَل مَن سَلَّم مِن رَكْعَتَيْن سَاهِيًا",
    order: 15,
    page: 98,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب إِتْمَام المُصَلِّي مَا ذَكَرَ إِذَا شَكَّ فِي صَلاَتِه",
    order: 16,
    page: 99,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب مَن قَامَ بَعْد الإِتْمَام أَو فِي الرَّكْعَتَيْن",
    order: 17,
    page: 101,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب النَّظَر فِي الصَّلاَة إِلَى مَا يَشْغَلُكَ عَنْهَا",
    order: 18,
    page: 101,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب تَشْدِيد فِي أَن يَمُرَّ أَحَد بَيْنَ يَدَي المُصَلِّي",
    order: 10,
    page: 147,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب الرُّخْصَة فِي المُرُور بَيْن يَدَي المُصَلِّي",
    order: 11,
    page: 148,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب سُتْرَة المُصَلِّي فِي السَّفَر",
    order: 12,
    page: 148,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب مَسْح الحَصْبَاء فِي الصَّلاَة",
    order: 13,
    page: 149,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب مَا جَاءَ فِي تَسْوِيَة الصُّفُوف",
    order: 14,
    page: 149,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب وَضْع اليَدَيْن إِحْدَاهُمَا عَلَى الأُخْرَى فِي الصَّلاَة",
    order: 15,
    page: 149,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب القُنُوت فِي الصُّبْح",
    order: 16,
    page: 150,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب النَّهْي عَن الصَّلاَة وَالإِنْسَان يُرِيد حَاجَة",
    order: 17,
    page: 150,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب انْتِظَار الصَّلاَة وَالمَشْي إِلَيْهَا",
    order: 18,
    page: 150,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب وَضْع اليَمِين عَلَى مَا يُوضَع عَلَيْه الوَجْه فِي السُّجُود",
    order: 19,
    page: 152,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب الِالتِفَات وَالتَّصْفِيق عِنْد الحَاجَة فِي الصَّلاَة",
    order: 20,
    page: 152,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب مَا يَفْعَل مَن جَاء وَالإِمَام رَاكِع",
    order: 21,
    page: 153,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب مَا جَاءَ فِي الصَّلاَة عَلَى النَّبِيّ ﷺ",
    order: 22,
    page: 154,
  },
  {
    bookSlug: "al-salah",
    name: "بَاب العَمَل فِي جَامِع الصَّلاَة",
    order: 23,
    page: 154,
  },
  { bookSlug: "al-salah", name: "بَاب جَامِع الصَّلاَة", order: 24, page: 157 },
  {
    bookSlug: "al-salah",
    name: "بَاب جَامِع التَّرْغِيب فِي الصَّلاَة",
    order: 25,
    page: 161,
  },

  // كتاب السهو
  {
    bookSlug: "al-sahw",
    name: "بَاب العَمَل فِي السَّهْو",
    order: 1,
    page: 103,
  },

  // كتاب الجمعة
  {
    bookSlug: "al-jumua",
    name: "بَاب العَمَل فِي غُسْل يَوْم الجُمُعَة",
    order: 1,
    page: 105,
  },
  {
    bookSlug: "al-jumua",
    name: "بَاب مَا جَاءَ فِي الإِنصَات يَوْم الجُمُعَة وَالإِمَام يَخْطُب",
    order: 2,
    page: 107,
  },
  {
    bookSlug: "al-jumua",
    name: "بَاب مَا جَاءَ فِيمَن أَدْرَكَ رَكْعَة يَوْم الجُمُعَة",
    order: 3,
    page: 108,
  },
  {
    bookSlug: "al-jumua",
    name: "بَاب مَا جَاءَ فِيمَن رَعَف يَوْم الجُمُعَة",
    order: 4,
    page: 109,
  },
  {
    bookSlug: "al-jumua",
    name: "بَاب السَّهْو فِي يَوْم الجُمُعَة",
    order: 5,
    page: 109,
  },
  {
    bookSlug: "al-jumua",
    name: "بَاب مَا جَاءَ فِي الإِمَام يَنْزِل يَوْم الجُمُعَة فِي السَّفَر",
    order: 6,
    page: 110,
  },
  {
    bookSlug: "al-jumua",
    name: "بَاب مَا جَاءَ فِي السَّاعَة الَّتِي فِي يَوْم الجُمُعَة",
    order: 7,
    page: 110,
  },
  {
    bookSlug: "al-jumua",
    name: "بَاب الهَيْئَة، وَتَخَطِّي الرِّقَاب، وَاسْتِقْبَال الإِمَام يَوْم الجُمُعَة",
    order: 8,
    page: 112,
  },
  {
    bookSlug: "al-jumua",
    name: "بَاب القِرَاءَة فِي صَلاَة الجُمُعَة، وَالأَحيَاء، وَمَن تَرَكَهَا مِن غَيْر عُذْر",
    order: 9,
    page: 112,
  },

  // كتاب الصلاة في رمضان
  {
    bookSlug: "al-salah-fi-ramadan",
    name: "بَاب التَّرْغِيب فِي الصَّلاَة فِي رَمَضَان",
    order: 1,
    page: 115,
  },
  {
    bookSlug: "al-salah-fi-ramadan",
    name: "بَاب مَا جَاءَ فِي قِيَام رَمَضَان",
    order: 2,
    page: 116,
  },

  // كتاب صلاة الليل
  {
    bookSlug: "salat-al-layl",
    name: "بَاب مَا جَاءَ فِي صَلاَة اللَّيْل",
    order: 1,
    page: 119,
  },
  {
    bookSlug: "salat-al-layl",
    name: "بَاب صَلاَة النَّبِيّ ﷺ فِي الوِتْر",
    order: 2,
    page: 120,
  },
  {
    bookSlug: "salat-al-layl",
    name: "بَاب الأَمْر بِالوِتْر",
    order: 3,
    page: 122,
  },
  {
    bookSlug: "salat-al-layl",
    name: "بَاب الوِتْر بَعْد الفَجْر",
    order: 4,
    page: 125,
  },
  {
    bookSlug: "salat-al-layl",
    name: "بَاب مَا جَاءَ فِي رَكْعَتَي الفَجْر",
    order: 5,
    page: 126,
  },

  // كتاب صلاة الجماعة
  {
    bookSlug: "salat-al-jamaa",
    name: "بَاب فَضْل صَلاَة الجَمَاعَة عَلَى صَلاَة الفَذِّ",
    order: 1,
    page: 129,
  },
  {
    bookSlug: "salat-al-jamaa",
    name: "بَاب مَا جَاءَ فِي العَتَمَة وَالصُّبْح",
    order: 2,
    page: 130,
  },
  {
    bookSlug: "salat-al-jamaa",
    name: "بَاب إِعَادَة الصَّلاَة مَعَ الإِمَام",
    order: 3,
    page: 131,
  },
  {
    bookSlug: "salat-al-jamaa",
    name: "بَاب العَمَل فِي صَلاَة الجَمَاعَة",
    order: 4,
    page: 133,
  },
  {
    bookSlug: "salat-al-jamaa",
    name: "بَاب صَلاَة الإِمَام وَهُوَ جَالِس",
    order: 5,
    page: 133,
  },
  {
    bookSlug: "salat-al-jamaa",
    name: "بَاب فَضْل صَلاَة القَائِم عَلَى صَلاَة القَاعِد",
    order: 6,
    page: 134,
  },
  {
    bookSlug: "salat-al-jamaa",
    name: "بَاب مَا جَاءَ فِي صَلاَة القَاعِد فِي النَّافِلَة",
    order: 7,
    page: 135,
  },
  {
    bookSlug: "salat-al-jamaa",
    name: "بَاب الصَّلاَة الوُسْطَى",
    order: 8,
    page: 135,
  },
  {
    bookSlug: "salat-al-jamaa",
    name: "بَاب الرُّخْصَة فِي الصَّلاَة فِي الثَّوْب الوَاحِد",
    order: 9,
    page: 136,
  },
  {
    bookSlug: "salat-al-jamaa",
    name: "بَاب الرُّخْصَة فِي صَلاَة المَرْأَة فِي الدِّرْع وَالخِمَار",
    order: 10,
    page: 137,
  },

  // كتاب قصر الصلاة في السفر
  {
    bookSlug: "qasr-al-salah-fi-al-safar",
    name: "بَاب الجَمْع بَيْن الصَّلاَتَيْن فِي الحَضَر وَالسَّفَر",
    order: 1,
    page: 139,
  },
  {
    bookSlug: "qasr-al-salah-fi-al-safar",
    name: "بَاب قَصْر الصَّلاَة فِي السَّفَر",
    order: 2,
    page: 141,
  },
  {
    bookSlug: "qasr-al-salah-fi-al-safar",
    name: "بَاب مَا يَجِب فِيه قَصْر الصَّلاَة",
    order: 3,
    page: 141,
  },
  {
    bookSlug: "qasr-al-salah-fi-al-safar",
    name: "بَاب صَلاَة المُسَافِر مَا لَم يُجْمِع مُكْثًا",
    order: 4,
    page: 143,
  },
  {
    bookSlug: "qasr-al-salah-fi-al-safar",
    name: "بَاب صَلاَة المُسَافِر إِذَا كَان إِمَامًا أَو أَجْمَع مُكْثًا",
    order: 5,
    page: 143,
  },
  {
    bookSlug: "qasr-al-salah-fi-al-safar",
    name: "بَاب صَلاَة المُسَافِر إِذَا كَان وَرَاء إِمَام",
    order: 6,
    page: 143,
  },
  {
    bookSlug: "qasr-al-salah-fi-al-safar",
    name: "بَاب صَلاَة النَّافِلَة فِي السَّفَر بِالنَّهَار وَاللَّيْل، وَالصَّلاَة عَلَى الدَّابَّة",
    order: 7,
    page: 144,
  },
  {
    bookSlug: "qasr-al-salah-fi-al-safar",
    name: "بَاب صَلاَة الضُّحَى",
    order: 8,
    page: 145,
  },
  {
    bookSlug: "qasr-al-salah-fi-al-safar",
    name: "بَاب جَامِع سُبْحَة الضُّحَى",
    order: 9,
    page: 146,
  },

  // كتاب العيدين
  {
    bookSlug: "al-eidayn",
    name: "بَاب العَمَل فِي غُسْل العِيدَيْن، وَالنِّدَاء فِيهِمَا، وَالإِقَامَة",
    order: 1,
    page: 163,
  },
  {
    bookSlug: "al-eidayn",
    name: "بَاب الأَمْر بِالصَّلاَة قَبْل الخُطْبَة فِي العِيدَيْن",
    order: 2,
    page: 163,
  },
  {
    bookSlug: "al-eidayn",
    name: "بَاب الأَمْر بِالأَكْل قَبْل الغُدُوّ إِلَى العِيد",
    order: 3,
    page: 164,
  },
  {
    bookSlug: "al-eidayn",
    name: "بَاب مَا جَاءَ فِي التَّكْبِير وَالقِرَاءَة فِي صَلاَة العِيدَيْن",
    order: 4,
    page: 164,
  },
  {
    bookSlug: "al-eidayn",
    name: "بَاب تَرْك الصَّلاَة قَبْل العِيدَيْن وَبَعْدَهُمَا",
    order: 5,
    page: 165,
  },
  {
    bookSlug: "al-eidayn",
    name: "بَاب الرُّخْصَة فِي الصَّلاَة قَبْل العِيدَيْن وَبَعْدَهُمَا",
    order: 6,
    page: 166,
  },
  {
    bookSlug: "al-eidayn",
    name: "بَاب غُدُوّ الإِمَام يَوْم العِيد وَانْتِظَار الخُطْبَة",
    order: 7,
    page: 166,
  },

  // كتاب صلاة الخوف
  {
    bookSlug: "salat-al-khawf",
    name: "بَاب صَلاَة الخَوْف",
    order: 1,
    page: 167,
  },

  // كتاب صلاة الكسوف
  {
    bookSlug: "salat-al-kusoof",
    name: "بَاب العَمَل فِي صَلاَة الكُسُوف",
    order: 1,
    page: 169,
  },
  {
    bookSlug: "salat-al-kusoof",
    name: "بَاب مَا جَاءَ فِي صَلاَة الكُسُوف",
    order: 2,
    page: 170,
  },

  // كتاب الاستسقاء
  {
    bookSlug: "al-istisqaa",
    name: "بَاب العَمَل فِي الاسْتِسْقَاء",
    order: 1,
    page: 173,
  },
  {
    bookSlug: "al-istisqaa",
    name: "بَاب مَا جَاءَ فِي الاسْتِسْقَاء",
    order: 2,
    page: 173,
  },
  {
    bookSlug: "al-istisqaa",
    name: "بَاب الاسْتِمْطَار بِالنُّجُوم",
    order: 3,
    page: 174,
  },

  // كتاب القبلة
  {
    bookSlug: "al-qibla",
    name: "بَاب النَّهْي عَن اسْتِقْبَال القِبْلَة، وَالإِنسَان عَلَى حَاجَته",
    order: 1,
    page: 177,
  },
  {
    bookSlug: "al-qibla",
    name: "بَاب الرُّخْصَة فِي اسْتِقْبَال القِبْلَة لِبَوْل أَو غَائِط",
    order: 2,
    page: 177,
  },
  {
    bookSlug: "al-qibla",
    name: "بَاب النَّهْي عَن البُصَاق فِي القِبْلَة",
    order: 3,
    page: 178,
  },
  {
    bookSlug: "al-qibla",
    name: "بَاب مَا جَاءَ فِي القِبْلَة",
    order: 4,
    page: 178,
  },
  {
    bookSlug: "al-qibla",
    name: "بَاب مَا جَاءَ فِي مَسْجِد النَّبِيّ ﷺ",
    order: 5,
    page: 179,
  },
  {
    bookSlug: "al-qibla",
    name: "بَاب مَا جَاءَ فِي خُرُوج النِّسَاء إِلَى المَسَاجِد",
    order: 6,
    page: 179,
  },

  // كتاب القرآن
  {
    bookSlug: "al-quran",
    name: "بَاب الأَمْر بِالوُضُوء لِمَن مَسَّ القُرْآن",
    order: 1,
    page: 181,
  },
  {
    bookSlug: "al-quran",
    name: "بَاب الرُّخْصَة فِي قِرَاءَة القُرْآن عَلَى غَيْر وُضُوء",
    order: 2,
    page: 181,
  },
  {
    bookSlug: "al-quran",
    name: "بَاب مَا جَاءَ فِي تَحْزِيب القُرْآن",
    order: 3,
    page: 182,
  },
  {
    bookSlug: "al-quran",
    name: "بَاب مَا جَاءَ فِي القُرْآن",
    order: 4,
    page: 182,
  },
  { bookSlug: "al-quran", name: "بَاب سُجُود القُرْآن", order: 5, page: 185 },
  {
    bookSlug: "al-quran",
    name: "بَاب مَا جَاءَ فِي قِرَاءَة ﴿قُلْ هُوَ اللَّهُ أَحَد﴾ وَ﴿تَبَارَكَ الَّذِي بِيَدِه المُلْك﴾",
    order: 6,
    page: 186,
  },
  {
    bookSlug: "al-quran",
    name: "بَاب مَا جَاءَ فِي ذِكْر اللَّه تَبَارَكَ وَتَعَالَى",
    order: 7,
    page: 187,
  },
  {
    bookSlug: "al-quran",
    name: "بَاب مَا جَاءَ فِي الدُّعَاء",
    order: 8,
    page: 189,
  },
  {
    bookSlug: "al-quran",
    name: "بَاب العَمَل فِي الدُّعَاء",
    order: 9,
    page: 191,
  },
  {
    bookSlug: "al-quran",
    name: "بَاب النَّهْي عَن الصَّلاَة بَعْد الصُّبْح وَبَعْد العَصْر",
    order: 10,
    page: 192,
  },

  // كتاب الجنائز
  { bookSlug: "al-janaaiz", name: "بَاب غُسْل المَيِّت", order: 1, page: 195 },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب مَا جَاءَ فِي كَفَن المَيِّت",
    order: 2,
    page: 196,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب المَشْي أَمَام الجَنَائِز",
    order: 3,
    page: 197,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب النَّهْي عَن أَن تُتَّبَع الجَنَازَة بِنَار",
    order: 4,
    page: 198,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب التَّكْبِير عَلَى الجَنَائِز",
    order: 5,
    page: 198,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب مَا يَقُول المُصَلِّي عَلَى الجَنَازَة",
    order: 6,
    page: 199,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب الصَّلاَة عَلَى الجَنَائِز بَعْد الصُّبْح إِلَى الإِشْرَاق، وَبَعْد العَصْر إِلَى الاصْفِرَار",
    order: 7,
    page: 199,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب الصَّلاَة عَلَى الجَنَائِز فِي المَسْجِد",
    order: 8,
    page: 200,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب جَامِع الصَّلاَة عَلَى الجَنَائِز",
    order: 9,
    page: 200,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب مَا جَاءَ فِي دَفْن المَيِّت",
    order: 10,
    page: 201,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب الوُقُوف لِلْجَنَائِز وَالجُلُوس عَلَى المَقَابِر",
    order: 11,
    page: 202,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب النَّهْي عَن البُكَاء عَلَى المَيِّت",
    order: 12,
    page: 203,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب الحُسْنَى فِي المُصِيبَة",
    order: 13,
    page: 204,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب جَامِع الحُسْنَى فِي المُصِيبَة",
    order: 14,
    page: 205,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب مَا جَاءَ فِي الاخْتِفَاء",
    order: 15,
    page: 206,
  },
  {
    bookSlug: "al-janaaiz",
    name: "بَاب جَامِع الجَنَائِز",
    order: 16,
    page: 206,
  },

  // كتاب الزكاة
  {
    bookSlug: "al-zakat",
    name: "بَاب مَا تَجِب فِيه الزَّكَاة",
    order: 1,
    page: 211,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب الزَّكَاة فِي العَيْن مِنَ الذَّهَب وَالوَرِق",
    order: 2,
    page: 212,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب الزَّكَاة فِي المَعَادِن",
    order: 3,
    page: 214,
  },
  { bookSlug: "al-zakat", name: "بَاب زَكَاة الرِّكَاز", order: 4, page: 215 },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَا لاَ زَكَاة فِيه مِنَ الحُلِيّ وَالتِّبْر وَالعَنْبَر",
    order: 5,
    page: 215,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب زَكَاة أَمْوَال اليَتَامَى، وَالتِّجَارَة لَهُم فِيهَا",
    order: 6,
    page: 216,
  },
  { bookSlug: "al-zakat", name: "بَاب زَكَاة المِيرَاث", order: 7, page: 216 },
  {
    bookSlug: "al-zakat",
    name: "بَاب الزَّكَاة فِي الدَّيْن",
    order: 8,
    page: 217,
  },
  { bookSlug: "al-zakat", name: "بَاب زَكَاة العُرُوض", order: 9, page: 218 },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَا جَاءَ فِي الكَنْز",
    order: 10,
    page: 219,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب صَدَقَة المَاشِيَة",
    order: 11,
    page: 220,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَا جَاءَ فِي صَدَقَة البَقَر",
    order: 12,
    page: 220,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب صَدَقَة الخُلَطَاء",
    order: 13,
    page: 223,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَا جَاءَ فِيمَا يُعَدّ بِه مِنَ السَّخْل فِي الصَّدَقَة",
    order: 14,
    page: 224,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب العَمَل فِي صَدَقَة عَامَيْن إِذَا اجْتَمَعَتَا",
    order: 15,
    page: 225,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب النَّهْي عَن التَّضْيِيق عَلَى النَّاس فِي الصَّدَقَة",
    order: 16,
    page: 226,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب أَخْذ الصَّدَقَة، وَمَن يَجُوز لَه أَخْذُهَا",
    order: 17,
    page: 226,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَا جَاءَ فِي أَخْذ الصَّدَقَات وَالتَّشْدِيد فِيهَا",
    order: 18,
    page: 227,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب زَكَاة مَا يُخْرَص مِن ثِمَار النَّخِيل وَالأَعْنَاب",
    order: 19,
    page: 228,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب زَكَاة الحُبُوب وَالزَّيْتُون",
    order: 20,
    page: 229,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَا لاَ زَكَاة فِيه مِنَ الثِّمَار",
    order: 21,
    page: 230,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَا لاَ زَكَاة فِيه مِنَ الفَوَاكِه وَالقَضْب وَالبُقُول",
    order: 22,
    page: 232,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَا جَاءَ فِي صَدَقَة الرَّقِيق وَالخَيْل وَالعَسَل",
    order: 23,
    page: 232,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب جِزْيَة أَهْل الكِتَاب وَالمَجُوس",
    order: 24,
    page: 234,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب عُشُور أَهْل الذِّمَّة",
    order: 25,
    page: 236,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب الشِّرَاء الصَّدَقَة وَالعَوْد فِيهَا",
    order: 26,
    page: 236,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَن تَجِب عَلَيْه زَكَاة الفِطْر",
    order: 27,
    page: 237,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَكِيلَة زَكَاة الفِطْر",
    order: 28,
    page: 237,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب وَقْت إِرْسَال زَكَاة الفِطْر",
    order: 29,
    page: 238,
  },
  {
    bookSlug: "al-zakat",
    name: "بَاب مَن لاَ تَجِب عَلَيْه زَكَاة الفِطْر",
    order: 30,
    page: 238,
  },

  // كتاب الصيام
  {
    bookSlug: "al-siyam",
    name: "بَاب مَا جَاءَ فِي رُؤْيَة الهِلاَل لِلصِّيَام وَالفِطْر فِي رَمَضَان",
    order: 1,
    page: 239,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب مَن أَجْمَع الصِّيَام قَبْل الفَجْر",
    order: 2,
    page: 240,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب مَا جَاءَ فِي تَعْجِيل الفِطْر",
    order: 3,
    page: 240,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب مَا جَاءَ فِي صِيَام الَّذِي يُصْبِح جُنُبًا",
    order: 4,
    page: 241,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب مَا جَاءَ فِي الرُّخْصَة لِلْقُبْلَة لِلصَّائِم",
    order: 5,
    page: 242,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب مَا جَاءَ فِي التَّشْدِيد فِي القُبْلَة لِلصَّائِم",
    order: 6,
    page: 243,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب مَا جَاءَ فِي الصِّيَام فِي السَّفَر",
    order: 7,
    page: 244,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب مَا يَفْعَل مَن قَدِم مِن سَفَر، أَو أَرَادَه فِي رَمَضَان",
    order: 8,
    page: 245,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب كَفَّارَة مَن أَفْطَرَ فِي رَمَضَان",
    order: 9,
    page: 246,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب مَا جَاءَ فِي حِجَامَة الصَّائِم",
    order: 10,
    page: 247,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب صِيَام يَوْم عَاشُورَاء",
    order: 11,
    page: 248,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب صِيَام يَوْم الفِطْر وَالأَضْحَى وَالدَّهْر",
    order: 12,
    page: 248,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب النَّهْي عَن الوِصَال فِي الصِّيَام",
    order: 13,
    page: 249,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب صِيَام الَّذِي يَقْتُل خَطَأً أَو يَظَاهِر",
    order: 14,
    page: 249,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب مَا يَفْعَل المَرِيض فِي صِيَامِه",
    order: 15,
    page: 250,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب النَّذْر فِي الصِّيَام، وَالصِّيَام عَن المَيِّت",
    order: 16,
    page: 250,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب مَا جَاءَ فِي قَضَاء رَمَضَان وَالكَفَّارَات",
    order: 17,
    page: 251,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب قَضَاء التَّطَوُّع",
    order: 18,
    page: 253,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب فِدْيَة مَن أَفْطَر فِي رَمَضَان مِن عِلَّة",
    order: 19,
    page: 254,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب جَامِع مَن أَفْطَرَ قَضَاء الصِّيَام",
    order: 20,
    page: 255,
  },
  {
    bookSlug: "al-siyam",
    name: "بَاب صِيَام اليَوْم الَّذِي يُشَكّ فِيه",
    order: 21,
    page: 255,
  },
  { bookSlug: "al-siyam", name: "بَاب جَامِع الصِّيَام", order: 22, page: 255 },

  // كتاب الاعتكاف
  {
    bookSlug: "al-itikaf",
    name: "بَاب ذِكْر الاعْتِكَاف",
    order: 1,
    page: 257,
  },
  {
    bookSlug: "al-itikaf",
    name: "بَاب مَا لاَ يَجُوز الاعْتِكَاف إِلاَّ بِه",
    order: 2,
    page: 259,
  },
];
